services:
  db:
    container_name: postgres_customer
    image: postgres:15
    environment:
      POSTGRES_USER: yeahbutstill
      POSTGRES_PASSWORD: 3sGnyr6UYUyrQah7uVwzLWec
      PGDATA: PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "$PWD/customer-data:/var/lib/postgresql/data"
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge
